project:
  type: website
  output-dir: docs

website:
  title: "hazelwood.dev"
  site-url: hazelwood.dev
  description: "Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/henkehazelwood/
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css



