project:
  type: website
  output-dir: docs

website:
  title: "data science and deep learning blog"
  base-url: https://hazelwood.dev
  description: "a data science and deeplearning blog by and for henke hazelwood"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css



